HW05 - Avatars
dawidmarek95x/nodejs-homework-template pull request #5
Opened 2022-11-12 04:53 UTC by dawidmarek95x

Major changes:
1. Added option to load the user's alternate avatar after registration and ability to change it at later stage by the user.
2. Unit tests for user registration and login were performed.

Please check.

2022-11-14 10:46 UTC, mkubera requested changes
ogolnie, swietnie :) Prosze o zmiany, bo ciekawi mnie to pytanie + masz tutaj potencjal do przepisania troche kodu na bardziej czytelny (a to jest dobry czas, zeby sie tego nauczyc, bo w pracy bedzie wieksza presja, wiec bedziesz mial mniej sposobnosci i czasu, zeby w ogole myslec o jakosci i czytelnosci kodu).

2022-11-14 10:46 UTC, mkubera commented on middlewares/pictures.js
> +    },
tu masz fajnego kandydata na zmiane myslenia o tym, jak czasem mozesz piszac kod, gdy pracujesz z Booleans :)
```js
      const mimetype = file.mimetype;
      const includesMimetype = mimetypeAllowedList.includes(mimetype);
      return cb(null, includesMimetype);
```
byc moze bedziesz chcial zmienic `includesMimetype` na cos, co ma wiecej sensu, ale pomysl skraca Ci sporo kodu, i jesli nazwiesz te stala odpowiednio (tak, zeby kazdy rozumial, ze to jest Bool).

2022-11-14 10:46 UTC, mkubera commented on middlewares/pictures.js
> +    },
odrobina ludzkiego piekna lezy tutaj w tym, ze mozna latwo zapytac "[it] `includesMimetype`?" -- "Yes? No?"
I dosc latwo dochodzimy do Prawda/Nieprawda :)

2022-11-14 10:46 UTC, mkubera commented on routes/api/contacts.js
> +);
To zaczyna wygladac malo czytelnie (i powtarza sie). Mysle, ze moglbys smialo zrobic destrukturyzacje na gorze pliku dla `validation` i `contactsController` (tym bardziej, ze plik nazywa sie `contacts.js`, wiec mala szansa, ze bedziesz tutaj trzymal inne routes), i wtedy robic:
`router.post("/", authMiddleware, creatingContact, addOne)`

Jezeli `creatingContact` jest semantycznie za malo jasne, to mozesz je zmienic np. na `validateCreation` albo (zeby dopasowac je do `addOne`, ktore masz) `validateAddition` (lub odwrotnie: przerob `addOne` na `createOne`).

2022-11-14 10:46 UTC, mkubera commented on services/users.js
> +  await User.findByIdAndUpdate(id, { avatarURL });
nie potrzebujesz tutaj dodac `return` (albo skrocic strzalke do prostego syntaxu)? 🤔

2022-11-14 19:16 UTC, dawidmarek95x commented
Dziękuję za cenny feedback. Wykonałem refaktoryzację kodu w miejscach, na które zwróciłeś uwagę oraz w innych, gdzie uznałem, że można zwiększyć ich czytelność. Teraz powinno być znacznie lepiej.

Proszę od weryfikację.

2022-11-15 11:17 UTC, mkubera requested changes

2022-11-15 11:17 UTC, mkubera commented on middlewares/pictures.js
> +      return cb(null, isCompatibleMimetype);
moze `hasCompatibleMimetype`? 🤔

2022-11-15 11:17 UTC, mkubera commented on routes/api/contacts.js
> +router.get("/", authMiddleware, getAll);
mysle, ze `authMiddleware` tez powinien byc lepiej nazwany. `authenticateUser`? (wiemy, ze to middleware, bo wpada jako druga funkcja w route (kazdy koder uzywajacy Express musi tak robic, wiec mozemy smialo zalozyc, ze ta czesc jest oczywista i nie wymaga wyjasnienia)).

2022-11-15 13:24 UTC, merged